package cadastrovendas;

import javax.swing.JOptionPane;

/**
 *
 * @author joao-
 */
public class Cadastro extends javax.swing.JFrame {

    public double valorveiculo = 0;
    public double valorversao = 0;
    public double valoracessorio = 0;
    public double totalacessorio = 0;
    public double acreversao = 0;
    public double totalveiculo = 0;
    public double resultado = 0;
    public String renda;
    public String comboveiculo;

    //Construtor
    public Cadastro() {
        initComponents();
    }

    //Roda todos os metodos que envolvem calculos e exibe o resultado final
    public void calculaVenda() {
        zeraVariavel();
        selecionaVeiculo();
        selecionaVersao();
        selecionaAcessorio();
        resultado = valorveiculo + valorversao + totalacessorio;
        txtExibeResultado.setText(String.valueOf(resultado));
    }
    
    //Zera as variaveis para não da problema na soma
    public void zeraVariavel() {
        valorveiculo = 0;
        valorversao = 0;
        valoracessorio = 0;
        totalacessorio = 0;
        totalveiculo = 0;
        resultado = 0;
    }

    //Calcula o valor do veiculo selecionado no ComboBox
    public void selecionaVeiculo() {
        if (cmbVeiculo.getSelectedIndex() == 0) {
            valorveiculo = 28990;
        }
        if (cmbVeiculo.getSelectedIndex() == 1) {
            valorveiculo = 35900;
        }
        if (cmbVeiculo.getSelectedIndex() == 2) {
            valorveiculo = 44990;
        }

    }

    //Calcula o valor da versao selecionada nos RadioButtons
    public void selecionaVersao() {
        if (rbtn10.isSelected()) {
            valorversao = 0;
        } else if (rbtn14.isSelected()) {
            valorversao = 2500;
        } else if (rbtn16.isSelected()) {
            valorversao = 4000;
        }
    }

    //Calcula os acessorios que marcados nas CheckBoxes
    public void selecionaAcessorio() {
        if (ckbArCondicionado.isSelected()) {
            valoracessorio = 2300;
            totalacessorio = valoracessorio + totalacessorio;
        }
        if (ckbRodas.isSelected()) {
            valoracessorio = 1200;
            totalacessorio = valoracessorio + totalacessorio;
        }
        if (ckbSom.isSelected()) {
            valoracessorio = 890;
            totalacessorio = valoracessorio + totalacessorio;
        }
        if (ckbVidros.isSelected()) {
            valoracessorio = 650;
            totalacessorio = valoracessorio + totalacessorio;
        }
    }

    //Apaga todo o conteudo dos campos que permitem preenchimento
    public void limpar() {
        txtCliente.setText("");
        txtProfissao.setText("");
        txtRenda.setText("");
        txtExibeResultado.setText("");

        //Deveria setar o resultado final para zero, para que não ficasse somando após o primeiro calculo, mas não o faz
        resultado = 0;
    }

    //Gera o relatório de compras, porém está INACABADO ainda
    public void gerarRelatorio() {
        String nomecliente;
        String profissao;
        nomecliente = txtCliente.getText();
        profissao = txtProfissao.getText();
        renda = txtRenda.getText();
        JOptionPane.showMessageDialog(null, "\n" + "Nome do Cliente: " + nomecliente + "\n"
                + "Profissao: " + profissao + "\n"
                + "Renda: " + renda, "RELATORIO DE VENDA", JOptionPane.PLAIN_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVersoes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtProfissao = new javax.swing.JTextField();
        txtRenda = new javax.swing.JTextField();
        cmbVeiculo = new javax.swing.JComboBox<>();
        btnExibir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rbtn10 = new javax.swing.JRadioButton();
        rbtn14 = new javax.swing.JRadioButton();
        rbtn16 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        ckbArCondicionado = new javax.swing.JCheckBox();
        ckbRodas = new javax.swing.JCheckBox();
        ckbSom = new javax.swing.JCheckBox();
        ckbVidros = new javax.swing.JCheckBox();
        txtExibeResultado = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Vendas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Cliente:");

        jLabel2.setText("Profissão:");

        jLabel3.setText("Veículo:");

        jLabel4.setText("Renda:");

        jLabel5.setText("Valor: R$");

        txtRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRendaActionPerformed(evt);
            }
        });

        cmbVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uno", "Gol", "Fiesta" }));
        cmbVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVeiculoActionPerformed(evt);
            }
        });

        btnExibir.setText("Exibir valor do veículo");
        btnExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirActionPerformed(evt);
            }
        });

        jLabel6.setText("Versões");

        btnVersoes.add(rbtn10);
        rbtn10.setText("1.0");
        rbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn10ActionPerformed(evt);
            }
        });

        btnVersoes.add(rbtn14);
        rbtn14.setText("1.4");

        btnVersoes.add(rbtn16);
        rbtn16.setText("1.6");

        jLabel7.setText("Acessórios");

        ckbArCondicionado.setText("Ar condicionado");
        ckbArCondicionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbArCondicionadoActionPerformed(evt);
            }
        });

        ckbRodas.setText("Rodas de liga leve");

        ckbSom.setText("Som");

        ckbVidros.setText("Vidros Elétricos");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnRelatorio.setText("Gerar Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtExibeResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProfissao)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRenda)
                            .addComponent(cmbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn10)
                            .addComponent(rbtn16)
                            .addComponent(rbtn14)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(ckbArCondicionado)
                            .addComponent(ckbRodas)
                            .addComponent(ckbSom)
                            .addComponent(ckbVidros)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtExibeResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtn10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtn14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtn16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbArCondicionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbRodas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbSom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbVidros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirActionPerformed
        // TODO add your handling code here:
        calculaVenda();
    }//GEN-LAST:event_btnExibirActionPerformed

    private void rbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn10ActionPerformed

    private void ckbArCondicionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbArCondicionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbArCondicionadoActionPerformed

    private void cmbVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVeiculoActionPerformed

    }//GEN-LAST:event_cmbVeiculoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        gerarRelatorio();
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void txtRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExibir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.ButtonGroup btnVersoes;
    private javax.swing.JCheckBox ckbArCondicionado;
    private javax.swing.JCheckBox ckbRodas;
    private javax.swing.JCheckBox ckbSom;
    private javax.swing.JCheckBox ckbVidros;
    private javax.swing.JComboBox<String> cmbVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rbtn10;
    private javax.swing.JRadioButton rbtn14;
    private javax.swing.JRadioButton rbtn16;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtExibeResultado;
    private javax.swing.JTextField txtProfissao;
    private javax.swing.JTextField txtRenda;
    // End of variables declaration//GEN-END:variables
}
